#!/usr/bin/env node
"use strict";
// O4 unified conventions overlay register generator (non-phase tooling).
//
//   node scripts/o4_register/generate.js [--check]
//
// Scans studies/*/output/*_summary.json for the `physicistReviewPending`
// field and emits docs/Phases/Adjudication/O4_CONVENTIONS_REGISTER.md, grouping
// every review-pending phase output by convention family so the O4 blast radius
// is machine-enumerable before the physicist session.
//
// STRICT INVARIANTS:
//   * READ-ONLY over committed artifacts. This tool never writes into studies/;
//     the committed JSONs stay byte-identical.
//   * Family classification is DERIVED (a heuristic overlay). The committed
//     phase outputs remain authoritative; the register carries a DERIVED flag
//     on every row and never mutates a source value.
//   * --check exits non-zero if the register on disk differs from freshly
//     generated content (for a pass to assert the register is current).
//
// This tooling directory (scripts/o4_register/) is registered in the
// scripts-root scanner exclusion helpers per the CLAUDE.md non-phase-tooling
// rule.

const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..", "..");
const studiesDir = path.join(repoRoot, "studies");
const outPath = path.join(repoRoot, "docs", "Phases", "Adjudication", "O4_CONVENTIONS_REGISTER.md");

// The four O4 families plus the two named extras (plan item 6). Classification
// is DERIVED from the phase id / subject kind; it is an overlay, not a source
// of truth.
const FAMILIES = [
  { key: "invariant-rays", title: "Invariant rays", match: (id, kind) => /ray|invariant/.test(id + kind) },
  { key: "positive-mode-ir-rule", title: "Positive-mode IR rule", match: (id, kind) => /gaussian|variational|positive|ir-|effective-potential/.test(id + kind) },
  { key: "theta-haar", title: "Theta-Haar measure", match: (id, kind) => /haar|theta/.test(id + kind) },
  { key: "saddle-backgrounds", title: "Saddle backgrounds", match: (id, kind) => /saddle|background|beyond-ray/.test(id + kind) },
  { key: "phase447-soft-floor", title: "phase447 soft-floor", match: (id) => /phase447/.test(id) },
  { key: "phase453-uniform-ladder", title: "phase453 uniform-ladder", match: (id) => /phase453/.test(id) },
];

function classify(id, kind) {
  const hay = (id + " " + kind).toLowerCase();
  const hits = FAMILIES.filter((f) => f.match(id.toLowerCase(), kind.toLowerCase())).map((f) => f.key);
  return hits.length ? hits : ["unclassified-pending"];
}

function listSummaryFiles() {
  const out = [];
  if (!fs.existsSync(studiesDir)) return out;
  for (const phase of fs.readdirSync(studiesDir).sort()) {
    const outDir = path.join(studiesDir, phase, "output");
    if (!fs.existsSync(outDir)) continue;
    for (const f of fs.readdirSync(outDir).sort()) {
      if (f.endsWith("_summary.json")) out.push(path.join(outDir, f));
    }
  }
  return out;
}

function collect() {
  const rows = [];
  for (const file of listSummaryFiles()) {
    let doc;
    try {
      doc = JSON.parse(fs.readFileSync(file, "utf8"));
    } catch {
      continue; // unreadable: skip (the phase's own gate covers integrity)
    }
    if (doc.physicistReviewPending !== true) continue;
    const id = String(doc.phaseId || path.basename(path.dirname(path.dirname(file))));
    const kind = String(doc.applicationSubjectKind || "");
    rows.push({
      phaseId: id,
      subjectKind: kind,
      terminalStatus: String(doc.terminalStatus || doc.verdictKind || ""),
      families: classify(id, kind),
      relPath: path.relative(repoRoot, file).replace(/\\/g, "/"),
    });
  }
  return rows.sort((a, b) => a.phaseId.localeCompare(b.phaseId));
}

function render(rows) {
  const byFamily = new Map();
  for (const fam of FAMILIES) byFamily.set(fam.key, []);
  byFamily.set("unclassified-pending", []);
  for (const r of rows) for (const fam of r.families) byFamily.get(fam)?.push(r);

  const lines = [];
  lines.push("# O4 Unified Conventions Overlay Register (generated)");
  lines.push("");
  lines.push("Machine-generated by `scripts/o4_register/generate.js` (plan item 6,");
  lines.push("`docs/Phases/WAVE2_ACTION_PLAN_2026-07-12.md`). It enumerates every phase");
  lines.push("output carrying `physicistReviewPending = true`, grouped by convention");
  lines.push("family, so the O4 blast radius is machine-enumerable before the physicist");
  lines.push("session.");
  lines.push("");
  lines.push("**DERIVED overlay.** Family classification is a DERIVED heuristic over the");
  lines.push("phase id / subject kind; it mutates nothing. The committed phase JSONs stay");
  lines.push("byte-identical and remain authoritative. Regenerate with");
  lines.push("`node scripts/o4_register/generate.js`; assert currency with `--check`.");
  lines.push("");
  lines.push(`Total review-pending phase outputs: **${rows.length}**.`);
  lines.push("");
  const famList = FAMILIES.map((f) => f.key).concat(["unclassified-pending"]);
  for (const key of famList) {
    const fam = FAMILIES.find((f) => f.key === key);
    const title = fam ? fam.title : "Unclassified (pending)";
    const items = byFamily.get(key) || [];
    lines.push(`## ${title} (${items.length})`);
    lines.push("");
    if (items.length === 0) {
      lines.push("_none_");
      lines.push("");
      continue;
    }
    lines.push("| phaseId | subjectKind | terminalStatus | source (DERIVED) |");
    lines.push("|---------|-------------|----------------|------------------|");
    for (const r of items) {
      lines.push(`| ${r.phaseId} | ${r.subjectKind} | ${r.terminalStatus} | \`${r.relPath}\` |`);
    }
    lines.push("");
  }
  lines.push("---");
  lines.push("");
  lines.push("One physicist sign-off over the families above sheds `physicistReviewPending`");
  lines.push("program-wide for the covered rows. Any overturn fail-closes exactly the");
  lines.push("pre-registered dependent list. Nothing here is promoted;");
  lines.push("`promotedPhysicalMassClaimCount = 0`.");
  lines.push("");
  return lines.join("\n");
}

function main() {
  const check = process.argv.includes("--check");
  const content = render(collect());
  if (check) {
    const existing = fs.existsSync(outPath) ? fs.readFileSync(outPath, "utf8") : "";
    if (existing !== content) {
      process.stderr.write("O4 register is stale; run: node scripts/o4_register/generate.js\n");
      process.exit(1);
    }
    process.stdout.write("O4 register is current.\n");
    return;
  }
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, content);
  process.stdout.write(`wrote ${path.relative(repoRoot, outPath)}\n`);
}

main();
